# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "38ac4edad2f9a1d002b465a66af6603c"
name = "promobanner"
application_url = "https://promobanner.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
# Gadget manages all your scopes, webhooks and api versioning for your app
# As such, this line should not be changed unless you are working with
# Shopify managed installations. Read more at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml
include_config_on_deploy = false

[auth]
redirect_urls = ["https://promobanner.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2025-07"
