import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyOrder" model, go to https://shopifyapp-dw5d.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Order",
  fields: {
    tracking: {
      type: "hasOne",
      child: { model: "orderTracking", belongsToField: "order" },
      storageKey: "Irm_5TCrjLCw::tqcneSxM99Zr",
    },
  },
  shopify: {
    fields: [
      "additionalFees",
      "alerts",
      "billingAddress",
      "billingStatusMatchesShippingAddress",
      "browserIp",
      "buyerAcceptsMarketing",
      "canMarkAsPaid",
      "canNotifyCustomer",
      "cancelReason",
      "cancellation",
      "cancelledAt",
      "capturable",
      "cartDiscountAmountSet",
      "cartToken",
      "checkoutToken",
      "clientDetails",
      "closed",
      "closedAt",
      "confirmationNumber",
      "confirmed",
      "currency",
      "currentCartDiscountAmountSet",
      "currentShippingPriceSet",
      "currentSubtotalLineItemsQuantity",
      "currentSubtotalPrice",
      "currentSubtotalPriceSet",
      "currentTotalAdditionalFeesSet",
      "currentTotalDiscounts",
      "currentTotalDiscountsSet",
      "currentTotalDutiesSet",
      "currentTotalPrice",
      "currentTotalPriceSet",
      "currentTotalTax",
      "currentTotalTaxSet",
      "currentTotalWeight",
      "customerJourneySummary",
      "customerLocale",
      "discountApplications",
      "discountCodes",
      "dutiesIncluded",
      "edited",
      "email",
      "estimatedTaxes",
      "financialStatus",
      "fulfillable",
      "fulfillmentStatus",
      "fulfillmentsCount",
      "fullyPaid",
      "hasTimelineComment",
      "landingSite",
      "legacyResourceId",
      "merchantEditable",
      "merchantEditableErrors",
      "merchantOfRecordAppId",
      "name",
      "netPaymentSet",
      "note",
      "noteAttributes",
      "orderStatusUrl",
      "originalTotalAdditionalFeesSet",
      "originalTotalDutiesSet",
      "originalTotalPriceSet",
      "paymentGatewayNames",
      "phone",
      "poNumber",
      "presentmentCurrency",
      "processedAt",
      "processingMethod",
      "referringSite",
      "refundDiscrepencySet",
      "refundable",
      "requiresShipping",
      "restockable",
      "returnStatus",
      "risk",
      "shippingAddress",
      "shop",
      "shopifyCreatedAt",
      "shopifyProtect",
      "shopifyUpdatedAt",
      "sourceIdentifier",
      "sourceName",
      "sourceUrl",
      "subtotalPrice",
      "subtotalPriceSet",
      "tags",
      "taxExempt",
      "taxLines",
      "taxesIncluded",
      "test",
      "token",
      "totalCapturableSet",
      "totalCashRoundingAdjustment",
      "totalDiscounts",
      "totalDiscountsSet",
      "totalLineItemsPrice",
      "totalLineItemsPriceSet",
      "totalOutstanding",
      "totalOutstandingSet",
      "totalPrice",
      "totalPriceSet",
      "totalReceivedSet",
      "totalRefundedSet",
      "totalRefundedShippingSet",
      "totalShippingPriceSet",
      "totalTax",
      "totalTaxSet",
      "totalTipReceived",
      "totalTipReceivedSet",
      "totalWeight",
      "transactionsCount",
      "unpaid",
    ],
  },
};
